import type { DesignConfig } from '../types';

export const PRESET_PREMIUM_CORPORATE: DesignConfig = {
  page: {
    size: 'A5',
    width: 148,
    height: 210,
    orientation: 'Portrait',
    margins: { top: 15, bottom: 15, left: 15, right: 15 },
  },
  background: {
    type: 'Solid',
    solidColor: '#F7F4EC',
    gradientColor1: '#F7F4EC',
    gradientColor2: '#FFFFFF',
    gradientDirection: 'to bottom',
    gradientOpacity: 1,
    imageUrl: '',
    imageFit: 'Cover',
    imageOpacity: 1,
    imagePositionX: 0,
    imagePositionY: 0,
    shapes: [
      {
        id: 'shape-1',
        enabled: true,
        type: 'Circle',
        x: 120,
        y: 10,
        width: 30,
        height: 30,
        rotation: 0,
        color: '#B08A3C',
        opacity: 0.15,
      },
      {
        id: 'shape-2',
        enabled: true,
        type: 'Rectangle',
        x: 10,
        y: 180,
        width: 60,
        height: 2,
        rotation: 0,
        color: '#D7DCE3',
        opacity: 0.5,
      },
    ],
  },
  typography: {
    documentTitle: {
      fontFamily: 'Georgia',
      fontSize: 28,
      fontWeight: 700,
      italic: false,
      color: '#18345A',
      letterSpacing: 0.5,
      lineHeight: 1.3,
      paragraphSpacingBefore: 0,
      paragraphSpacingAfter: 8,
      alignment: 'Center',
    },
    subtitle: {
      fontFamily: 'Georgia',
      fontSize: 14,
      fontWeight: 400,
      italic: true,
      color: '#6B7280',
      letterSpacing: 0,
      lineHeight: 1.5,
      paragraphSpacingBefore: 0,
      paragraphSpacingAfter: 12,
      alignment: 'Center',
    },
    partTitle: {
      fontFamily: 'Georgia',
      fontSize: 24,
      fontWeight: 700,
      italic: false,
      color: '#18345A',
      letterSpacing: 0.3,
      lineHeight: 1.4,
      paragraphSpacingBefore: 12,
      paragraphSpacingAfter: 8,
      alignment: 'Left',
    },
    articleTitle: {
      fontFamily: 'Georgia',
      fontSize: 18,
      fontWeight: 600,
      italic: false,
      color: '#18345A',
      letterSpacing: 0.2,
      lineHeight: 1.4,
      paragraphSpacingBefore: 10,
      paragraphSpacingAfter: 6,
      alignment: 'Left',
    },
    sectionTitle: {
      fontFamily: 'Helvetica',
      fontSize: 13,
      fontWeight: 700,
      italic: false,
      color: '#A91E3A',
      letterSpacing: 0.8,
      lineHeight: 1.3,
      paragraphSpacingBefore: 8,
      paragraphSpacingAfter: 6,
      alignment: 'Left',
    },
    body: {
      fontFamily: 'Georgia',
      fontSize: 10,
      fontWeight: 400,
      italic: false,
      color: '#303030',
      letterSpacing: 0,
      lineHeight: 1.6,
      paragraphSpacingBefore: 0,
      paragraphSpacingAfter: 8,
      alignment: 'Justify',
    },
    leadParagraph: {
      fontFamily: 'Georgia',
      fontSize: 11,
      fontWeight: 500,
      italic: false,
      color: '#303030',
      letterSpacing: 0,
      lineHeight: 1.6,
      paragraphSpacingBefore: 0,
      paragraphSpacingAfter: 8,
      alignment: 'Justify',
    },
    caption: {
      fontFamily: 'Helvetica',
      fontSize: 8,
      fontWeight: 400,
      italic: true,
      color: '#6B7280',
      letterSpacing: 0,
      lineHeight: 1.4,
      paragraphSpacingBefore: 0,
      paragraphSpacingAfter: 4,
      alignment: 'Left',
    },
    tableHeader: {
      fontFamily: 'Helvetica',
      fontSize: 9,
      fontWeight: 700,
      italic: false,
      color: '#FFFFFF',
      letterSpacing: 0,
      lineHeight: 1.4,
      paragraphSpacingBefore: 0,
      paragraphSpacingAfter: 0,
      alignment: 'Center',
    },
    tableBody: {
      fontFamily: 'Helvetica',
      fontSize: 9,
      fontWeight: 400,
      italic: false,
      color: '#303030',
      letterSpacing: 0,
      lineHeight: 1.4,
      paragraphSpacingBefore: 0,
      paragraphSpacingAfter: 0,
      alignment: 'Left',
    },
    header: {
      fontFamily: 'Helvetica',
      fontSize: 8,
      fontWeight: 500,
      italic: false,
      color: '#6B7280',
      letterSpacing: 0,
      lineHeight: 1.3,
      paragraphSpacingBefore: 0,
      paragraphSpacingAfter: 0,
      alignment: 'Center',
    },
    footer: {
      fontFamily: 'Helvetica',
      fontSize: 8,
      fontWeight: 400,
      italic: false,
      color: '#6B7280',
      letterSpacing: 0,
      lineHeight: 1.3,
      paragraphSpacingBefore: 0,
      paragraphSpacingAfter: 0,
      alignment: 'Center',
    },
  },
  colors: {
    primary: '#18345A',
    secondary: '#A91E3A',
    accent: '#B08A3C',
    heading: '#18345A',
    body: '#303030',
    muted: '#6B7280',
    background: '#F7F4EC',
    tableHeader: '#18345A',
    tableBody: '#F9F9F9',
    border: '#D7DCE3',
    footer: '#6B7280',
    highlight: '#B08A3C',
  },
  logo: {
    enabled: false,
    source: '',
    width: 80,
    height: 40,
    x: 10,
    y: 10,
    opacity: 1,
    keepAspectRatio: true,
    position: 'TopLeft',
  },
  header: {
    enabled: true,
    leftContent: '',
    centerContent: 'Professional Document',
    rightContent: '',
    fontFamily: 'Helvetica',
    fontSize: 8,
    color: '#6B7280',
    spacing: 6,
    borderEnabled: true,
    borderThickness: 1,
    borderColor: '#D7DCE3',
    includeLogo: false,
  },
  footer: {
    enabled: true,
    leftContent: '',
    centerContent: '',
    rightContent: 'Page {page}',
    fontFamily: 'Helvetica',
    fontSize: 8,
    color: '#6B7280',
    spacing: 6,
    borderEnabled: true,
    borderThickness: 1,
    borderColor: '#D7DCE3',
    includePageNumber: true,
  },
  pageNumber: {
    enabled: true,
    format: 'Arabic',
    position: 'BottomRight',
    fontFamily: 'Helvetica',
    fontSize: 8,
    color: '#6B7280',
  },
  table: {
    headerBackground: '#18345A',
    headerTextColor: '#FFFFFF',
    bodyBackground: '#FFFFFF',
    bodyTextColor: '#303030',
    borderColor: '#D7DCE3',
    borderThickness: 1,
    cellPadding: 6,
    fontFamily: 'Helvetica',
    fontSize: 9,
    rowSpacing: 1,
    stripedRows: true,
  },
};

export const PRESET_MODERN: DesignConfig = {
  ...PRESET_PREMIUM_CORPORATE,
  background: {
    ...PRESET_PREMIUM_CORPORATE.background,
    solidColor: '#FFFFFF',
    shapes: [],
  },
  typography: {
    ...PRESET_PREMIUM_CORPORATE.typography,
    documentTitle: {
      ...PRESET_PREMIUM_CORPORATE.typography.documentTitle,
      fontFamily: 'Poppins',
      fontSize: 32,
      fontWeight: 600,
    },
    sectionTitle: {
      ...PRESET_PREMIUM_CORPORATE.typography.sectionTitle,
      fontFamily: 'Poppins',
      fontSize: 14,
      fontWeight: 600,
    },
  },
  colors: {
    ...PRESET_PREMIUM_CORPORATE.colors,
    primary: '#1F2937',
    secondary: '#3B82F6',
    accent: '#F59E0B',
    background: '#FFFFFF',
  },
};

export const PRESET_MINIMAL: DesignConfig = {
  ...PRESET_PREMIUM_CORPORATE,
  background: {
    type: 'Solid',
    solidColor: '#FFFFFF',
    gradientColor1: '#FFFFFF',
    gradientColor2: '#FFFFFF',
    gradientDirection: 'to bottom',
    gradientOpacity: 1,
    imageUrl: '',
    imageFit: 'Cover',
    imageOpacity: 1,
    imagePositionX: 0,
    imagePositionY: 0,
    shapes: [],
  },
  typography: {
    ...PRESET_PREMIUM_CORPORATE.typography,
    documentTitle: {
      ...PRESET_PREMIUM_CORPORATE.typography.documentTitle,
      fontSize: 20,
      fontWeight: 600,
    },
  },
  colors: {
    ...PRESET_PREMIUM_CORPORATE.colors,
    background: '#FFFFFF',
    body: '#000000',
    muted: '#666666',
  },
  header: {
    ...PRESET_PREMIUM_CORPORATE.header,
    borderEnabled: false,
  },
  footer: {
    ...PRESET_PREMIUM_CORPORATE.footer,
    borderEnabled: false,
  },
};

export const PRESET_ENGINEERING: DesignConfig = {
  ...PRESET_PREMIUM_CORPORATE,
  background: {
    type: 'Solid',
    solidColor: '#F5F5F5',
    gradientColor1: '#F5F5F5',
    gradientColor2: '#FFFFFF',
    gradientDirection: 'to bottom',
    gradientOpacity: 1,
    imageUrl: '',
    imageFit: 'Cover',
    imageOpacity: 1,
    imagePositionX: 0,
    imagePositionY: 0,
    shapes: [],
  },
  colors: {
    ...PRESET_PREMIUM_CORPORATE.colors,
    primary: '#2C3E50',
    secondary: '#E74C3C',
    accent: '#3498DB',
    background: '#F5F5F5',
  },
};

export const PRESET_LEGAL_GOVERNANCE: DesignConfig = {
  ...PRESET_PREMIUM_CORPORATE,
  typography: {
    ...PRESET_PREMIUM_CORPORATE.typography,
    body: {
      ...PRESET_PREMIUM_CORPORATE.typography.body,
      lineHeight: 1.8,
      alignment: 'Justify',
    },
  },
  colors: {
    ...PRESET_PREMIUM_CORPORATE.colors,
    primary: '#1A3A52',
    secondary: '#7B3F39',
  },
};

export const presets = {
  'Premium Corporate': PRESET_PREMIUM_CORPORATE,
  Modern: PRESET_MODERN,
  Minimal: PRESET_MINIMAL,
  Engineering: PRESET_ENGINEERING,
  'Legal / Governance': PRESET_LEGAL_GOVERNANCE,
};

export type PresetName = keyof typeof presets;
